### ISSUE TITLE
Feature request - support string when passing ID to setup

### ISSUE THREAD

**Issue by mwargan** [henk-badenhorst/vue-hotjar-next#16]
While easy to "fix" with `Number(import.meta.env.VITE_HOTJAR_MEASUREMENT_ID)` - the assumption by this plugin is wrong. It's possible that the HotJar ID starts with 00123, and if we convert it to a number in Javascript, it'll remove the leading 0's.

This plugin should allow strings as an ID, it's a more fitting type for this use case.

**Comment by henk-badenhorst** [comment]
Thanks for the input but I am not making an assumption. If you look at the `hjid` in the [Hotjar snippet](https://help.hotjar.com/hc/en-us/articles/115009336727-How-to-Install-Your-Hotjar-Tracking-Code) it is a number. So this is not an assumption this plugin is making. It is by design to prevent type conversions. I have yet to see a HotJar ID starting with leading zeros and if this is the case this then would be a bug on their side as the Hotjar snippet takes in a number type as `hjid`.

**Comment by mwargan** [comment]
You're right - don't know why I didn't check their original code.

I'll change this to a feature request on expanding supported types (e.g. converting as required on the plugins side) - I think it could be helpful as the most common place people will define their IDs are in an ENV file which gives us strings.

I'll see if I can make an MR if you're onboard with the idea.

**Comment by henk-badenhorst** [comment]
Apologies for the delayed response. Feel free to submit a Pull Request. It would have to support both strings and numbers to prevent this from being a breaking change.

**Comment by mwargan** [comment]
@henk-badenhorst all done! https://github.com/henk-badenhorst/vue-hotjar-next/pull/17

**Comment by henk-badenhorst** [comment]
Sorry, I was AFK for a while. Thank you, I will review this and test it in the coming week and publish a new release.

**Comment by henk-badenhorst** [comment]
Version [2.1](https://github.com/henk-badenhorst/vue-hotjar-next/releases/tag/v2.1.0) contains your contribution. Thank you for the suggestion and contribution.
